# all_packages.yaml
# Kombiniert alle Packages in einer Datei (Workaround für ESPHome 2026.2.0)

# === Hardware (devices/JC3248W535.yaml) ===
spi:
  - type: quad
    clk_pin: 47
    data_pins: [21, 48, 40, 39]

i2c:
  - sda: 4
    scl: 8
    scan: true

output:
  - id: gpio_backlight_pwm
    platform: ledc
    pin: 1
    frequency: 1000Hz

light:
  - id: backlight
    name: Backlight
    platform: monochromatic
    output: gpio_backlight_pwm
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

display:
  - id: main_display
    platform: mipi_spi
    model: JC3248W535
    data_rate: 40MHz
    update_interval: never
    auto_clear_enabled: false

touchscreen:
  - id: main_touchscreen
    platform: axs15231

# === Common (common.yaml) ===
web_server:
  port: 80

time:
  - platform: homeassistant
    id: ha_time
    timezone: Europe/Berlin

switch:
  - platform: restart
    name: "Restart"
    entity_category: config

binary_sensor:
  - platform: status
    name: "Status"
    entity_category: diagnostic

sensor:
  - id: wifi_signal_db
    name: "WiFi Signal"
    platform: wifi_signal
    update_interval: 60s
    entity_category: diagnostic
  
  - platform: template
    name: "WiFi Strength"
    id: wifi_strength
    unit_of_measurement: "%"
    update_interval: 60s
    entity_category: diagnostic
    lambda: |-
      if (id(wifi_signal_db).state) {
        return min(max(2 * (id(wifi_signal_db).state + 100.0), 0.0), 100.0);
      } else {
        return 0.0;
      }

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
      id: ip_address
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
      id: connected_ssid
    mac_address:
      name: "Mac Address"
      entity_category: diagnostic
      id: mac_address
  
  - platform: template
    name: "Current Time Badge"
    id: current_time_badge
    update_interval: 1s
    lambda: |-
      auto time = id(ha_time).now();
      return str_sprintf("%02d:%02d", time.hour, time.minute);
  
  - platform: template
    name: "Current Date"
    id: current_date
    update_interval: 60s
    lambda: |-
      auto time = id(ha_time).now();
      static const char * const months[] = {"Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"};
      return str_sprintf("%02d. %s %04d", time.day_of_month, months[time.month-1], time.year);

globals:
  - id: homeassistant_ip
    type: std::string
    initial_value: '""'

# === Layout & Pages ===
# Diese müssen als separate includes bleiben wegen Größe
# Werden in guition-display.yaml direkt referenziert
