# common.yaml
# Gemeinsame ESPHome-Konfiguration für alle Geräte

esphome:
  min_version: 2024.11.0

# Web-Server für direkten Geräte-Zugriff
web_server:
  port: 80

# Standard-Sensoren und Schalter
switch:
  - platform: restart
    name: "Restart"
    entity_category: config

binary_sensor:
  - platform: status
    name: "Status"
    entity_category: diagnostic

# WiFi-Signal-Stärke
sensor:
  - id: wifi_signal_db
    name: "WiFi Signal"
    platform: wifi_signal
    update_interval: 60s
    entity_category: diagnostic

  - id: wifi_signal_strength
    name: "WiFi Strength"
    platform: copy
    source_id: wifi_signal_db
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic

# Netzwerk-Informationen
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      entity_category: diagnostic

# Globale Variable für Home Assistant IP
globals:
  - id: homeassistant_ip
    type: std::string
    initial_value: '""'
