# guition-display-complete.yaml
# 🎉 VOLLSTÄNDIGE VERSION - HOCHFORMAT (320x480)
# Rotation: 90 Grad für physisches Hochformat

esphome:
  name: guition-display
  friendly_name: Guition Display
  min_version: 2024.11.0
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: backlight
          brightness: 80%
      - delay: 1s
      - lvgl.page.show: page_lights

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

# === HARDWARE ===
spi:
  - type: quad
    clk_pin: 47
    data_pins: [21, 48, 40, 39]

i2c:
  - sda: 4
    scl: 8
    scan: true

output:
  - id: gpio_backlight_pwm
    platform: ledc
    pin: 1
    frequency: 1000Hz

light:
  - id: backlight
    name: Backlight
    platform: monochromatic
    output: gpio_backlight_pwm
    restore_mode: ALWAYS_ON

display:
  - id: main_display
    platform: mipi_spi
    model: JC3248W535
    data_rate: 40MHz
    rotation: 90
    update_interval: never
    auto_clear_enabled: false

touchscreen:
  - id: main_touchscreen
    platform: axs15231

web_server:
  port: 80

time:
  - platform: homeassistant
    id: ha_time
    timezone: Europe/Berlin

# === WIFI ===
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Guition-Display"

captive_portal:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: INFO
  logs:
    component: ERROR
    lvgl: WARN

# === FONTS ===
font:
  - file: "gfonts://Roboto"
    id: roboto_12
    size: 12
    glyphs: "!\"%()+*,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzäöüÄÖÜß@&/<>"
  
  - file: "gfonts://Roboto"
    id: roboto_14
    size: 14
    glyphs: "!\"%()+*,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzäöüÄÖÜß@&/<>"
  
  - file: "gfonts://Roboto"
    id: roboto_16
    size: 16
    glyphs: "!\"%()+*,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzäöüÄÖÜß@&/<>"
  
  - file: "gfonts://Roboto@700"
    id: roboto_bold_18
    size: 18
    glyphs: "!\"%()+*,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzäöüÄÖÜß@&/<>"
  
  - file: "gfonts://Roboto@700"
    id: roboto_bold_24
    size: 24
    glyphs: "!\"%()+*,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzäöüÄÖÜß@&/<>"

# === SENSOREN ===
text_sensor:
  - platform: template
    id: current_time_badge
    update_interval: 1s
    lambda: |-
      auto time = id(ha_time).now();
      return str_sprintf("%02d:%02d", time.hour, time.minute);
  
  - platform: wifi_info
    ip_address:
      id: ip_address
      entity_category: diagnostic
  
  - platform: homeassistant
    entity_id: weather.forecast_home
    id: weather_condition
    internal: true
    on_value:
      - lvgl.label.update:
          id: weather_condition_label
          text: !lambda |-
            return x.c_str();

sensor:
  - platform: wifi_signal
    id: wifi_signal_db
    update_interval: 60s
  
  - platform: template
    id: wifi_strength
    unit_of_measurement: "%"
    update_interval: 60s
    lambda: |-
      if (id(wifi_signal_db).state) {
        return min(max(2 * (id(wifi_signal_db).state + 100.0), 0.0), 100.0);
      } else {
        return 0.0;
      }
  
  - platform: homeassistant
    entity_id: light.alle_lichter_2
    attribute: brightness
    id: alle_lichter_brightness
    internal: true
    on_value:
      - lvgl.slider.update:
          id: slider_alle_lichter
          value: !lambda return x / 2.55;
  
  - platform: homeassistant
    entity_id: climate.wohnzimmer_thermostat
    attribute: current_temperature
    id: wz_current_temp
    internal: true
    on_value:
      - lvgl.label.update:
          id: wz_current_label
          text: !lambda |-
            return str_sprintf("%.1f C", x);
  
  - platform: homeassistant
    entity_id: climate.wohnzimmer_thermostat
    attribute: temperature
    id: wz_target_temp
    internal: true
    on_value:
      - lvgl.label.update:
          id: wz_target_label
          text: !lambda |-
            return str_sprintf("Ziel: %.1f C", x);
  
  - platform: homeassistant
    entity_id: climate.schlafzimmer_thermostat
    attribute: current_temperature
    id: sz_current_temp
    internal: true
    on_value:
      - lvgl.label.update:
          id: sz_current_label
          text: !lambda |-
            return str_sprintf("%.1f C", x);
  
  - platform: homeassistant
    entity_id: climate.schlafzimmer_thermostat
    attribute: temperature
    id: sz_target_temp
    internal: true
    on_value:
      - lvgl.label.update:
          id: sz_target_label
          text: !lambda |-
            return str_sprintf("Ziel: %.1f C", x);
  
  - platform: homeassistant
    entity_id: weather.forecast_home
    attribute: temperature
    id: weather_temp
    internal: true
    on_value:
      - lvgl.label.update:
          id: weather_temp_label
          text: !lambda |-
            return str_sprintf("%.0f C", x);

# === BINARY SENSOREN ===
binary_sensor:
  - platform: homeassistant
    entity_id: light.alle_lichter_2
    id: alle_lichter_state
    internal: true
    on_state:
      - lvgl.widget.update:
          id: btn_alle_lichter
          bg_color: !lambda |-
            return lv_color_hex(x ? 0xFFAA00 : 0x333333);
  
  - platform: homeassistant
    entity_id: light.stehlampe_bibi
    id: stehlampe_bibi_state
    internal: true
    on_state:
      - lvgl.widget.update:
          id: btn_stehlampe_bibi
          bg_color: !lambda |-
            return lv_color_hex(x ? 0xFFAA00 : 0x333333);
  
  - platform: homeassistant
    entity_id: light.garderobe_licht
    id: garderobe_state
    internal: true
    on_state:
      - lvgl.widget.update:
          id: btn_garderobe
          bg_color: !lambda |-
            return lv_color_hex(x ? 0xFFAA00 : 0x333333);
  
  - platform: homeassistant
    entity_id: light.licht_wohnzimmerschrank
    id: wohnzimmer_state
    internal: true
    on_state:
      - lvgl.widget.update:
          id: btn_wohnzimmer
          bg_color: !lambda |-
            return lv_color_hex(x ? 0xFFAA00 : 0x333333);
  
  - platform: homeassistant
    entity_id: light.esszimmer_licht
    id: esszimmer_state
    internal: true
    on_state:
      - lvgl.widget.update:
          id: btn_esszimmer
          bg_color: !lambda |-
            return lv_color_hex(x ? 0xFFAA00 : 0x333333);
  
  - platform: homeassistant
    entity_id: light.kuchen_unterlicht
    id: kueche_state
    internal: true
    on_state:
      - lvgl.widget.update:
          id: btn_kueche
          bg_color: !lambda |-
            return lv_color_hex(x ? 0xFFAA00 : 0x333333);
  
  - platform: homeassistant
    entity_id: light.kajplats_e27_ws_globe_470lm
    id: flur_state
    internal: true
    on_state:
      - lvgl.widget.update:
          id: btn_flur
          bg_color: !lambda |-
            return lv_color_hex(x ? 0xFFAA00 : 0x333333);
  
  - platform: homeassistant
    entity_id: light.licht_aktenschrank_markus
    id: aktenschrank_state
    internal: true
    on_state:
      - lvgl.widget.update:
          id: btn_aktenschrank
          bg_color: !lambda |-
            return lv_color_hex(x ? 0xFFAA00 : 0x333333);
  
  - platform: homeassistant
    entity_id: light.bibis_ecke_licht
    id: bibis_ecke_state
    internal: true
    on_state:
      - lvgl.widget.update:
          id: btn_bibis_ecke
          bg_color: !lambda |-
            return lv_color_hex(x ? 0xFFAA00 : 0x333333);

# === LVGL (320x480 Hochformat) ===
lvgl:
  log_level: WARN
  displays:
    - main_display
  touchscreens:
    - touchscreen_id: main_touchscreen
  color_depth: 16
  default_font: roboto_14
  buffer_size: 25%
  
  # Header (320px breit)
  top_layer:
    widgets:
      - obj:
          id: header_bar
          x: 0
          y: 0
          width: 320
          height: 35
          bg_color: 0x1a1a1a
          border_width: 0
          pad_all: 3
          widgets:
            # Zurück-Button
            - button:
                id: btn_nav_prev
                x: 2
                y: 2
                width: 40
                height: 30
                bg_color: 0x333333
                radius: 5
                on_click:
                  - lvgl.page.previous:
                widgets:
                  - label:
                      text: "<"
                      text_font: roboto_bold_18
                      align: CENTER
            
            # Uhrzeit
            - label:
                id: time_label
                x: 50
                y: 5
                text_font: roboto_bold_18
                text: "00:00"
            
            # Titel
            - label:
                id: page_title
                x: 130
                y: 7
                text_font: roboto_14
                text_color: 0xAAAAAA
                text: "Lampen"
            
            # WiFi
            - label:
                id: wifi_label
                x: 245
                y: 7
                text_font: roboto_12
                text_color: 0xAAAAAA
                text: "..."
            
            # Vorwärts-Button
            - button:
                id: btn_nav_next
                x: 278
                y: 2
                width: 40
                height: 30
                bg_color: 0x333333
                radius: 5
                on_click:
                  - lvgl.page.next:
                widgets:
                  - label:
                      text: ">"
                      text_font: roboto_bold_18
                      align: CENTER
  
  # === SEITEN ===
  pages:
    # === LAMPEN (2 Spalten) ===
    - id: page_lights
      bg_color: 0x000000
      pad_all: 5
      pad_top: 40
      widgets:
        # Alle Lichter
        - obj:
            width: 310
            height: 70
            bg_color: 0x333333
            radius: 8
            pad_all: 8
            clickable: true
            id: btn_alle_lichter
            on_click:
              - homeassistant.service:
                  service: light.toggle
                  data:
                    entity_id: light.alle_lichter_2
            widgets:
              - label:
                  text: "Alle Lichter"
                  text_font: roboto_bold_18
                  align: TOP_LEFT
              - slider:
                  id: slider_alle_lichter
                  width: 90%
                  height: 15
                  align: BOTTOM_MID
                  y: -3
                  min_value: 0
                  max_value: 100
                  on_release:
                    - homeassistant.service:
                        service: light.turn_on
                        data:
                          entity_id: light.alle_lichter_2
                          brightness: !lambda return int(x * 2.55);
        
        # Grid 2x5 (9 Lampen)
        - obj:
            width: 310
            y: 75
            height: 400
            bg_color: 0x000000
            border_width: 0
            layout:
              type: GRID
              grid_columns: [150, 150]
              grid_rows: [75, 75, 75, 75, 75]
              pad_column: 10
              pad_row: 8
            widgets:
              - button:
                  id: btn_stehlampe_bibi
                  bg_color: 0x333333
                  radius: 8
                  on_click:
                    - homeassistant.service:
                        service: light.toggle
                        data:
                          entity_id: light.stehlampe_bibi
                  widgets:
                    - label:
                        text: "Stehlampe\nBibi"
                        text_font: roboto_14
                        align: CENTER
              
              - button:
                  id: btn_garderobe
                  bg_color: 0x333333
                  radius: 8
                  on_click:
                    - homeassistant.service:
                        service: light.toggle
                        data:
                          entity_id: light.garderobe_licht
                  widgets:
                    - label:
                        text: "Garderobe"
                        text_font: roboto_14
                        align: CENTER
              
              - button:
                  id: btn_wohnzimmer
                  bg_color: 0x333333
                  radius: 8
                  on_click:
                    - homeassistant.service:
                        service: light.toggle
                        data:
                          entity_id: light.licht_wohnzimmerschrank
                  widgets:
                    - label:
                        text: "Wohnzimmer\nSchrank"
                        text_font: roboto_14
                        align: CENTER
              
              - button:
                  id: btn_esszimmer
                  bg_color: 0x333333
                  radius: 8
                  on_click:
                    - homeassistant.service:
                        service: light.toggle
                        data:
                          entity_id: light.esszimmer_licht
                  widgets:
                    - label:
                        text: "Esszimmer"
                        text_font: roboto_14
                        align: CENTER
              
              - button:
                  id: btn_kueche
                  bg_color: 0x333333
                  radius: 8
                  on_click:
                    - homeassistant.service:
                        service: light.toggle
                        data:
                          entity_id: light.kuchen_unterlicht
                  widgets:
                    - label:
                        text: "Kueche\nUnter"
                        text_font: roboto_14
                        align: CENTER
              
              - button:
                  id: btn_flur
                  bg_color: 0x333333
                  radius: 8
                  on_click:
                    - homeassistant.service:
                        service: light.toggle
                        data:
                          entity_id: light.kajplats_e27_ws_globe_470lm
                  widgets:
                    - label:
                        text: "Flur"
                        text_font: roboto_14
                        align: CENTER
              
              - button:
                  id: btn_aktenschrank
                  bg_color: 0x333333
                  radius: 8
                  on_click:
                    - homeassistant.service:
                        service: light.toggle
                        data:
                          entity_id: light.licht_aktenschrank_markus
                  widgets:
                    - label:
                        text: "Akten\nMarkus"
                        text_font: roboto_14
                        align: CENTER
              
              - button:
                  id: btn_bibis_ecke
                  bg_color: 0x333333
                  radius: 8
                  on_click:
                    - homeassistant.service:
                        service: light.toggle
                        data:
                          entity_id: light.bibis_ecke_licht
                  widgets:
                    - label:
                        text: "Bibis\nEcke"
                        text_font: roboto_14
                        align: CENTER
      
      on_load:
        - lvgl.label.update:
            id: page_title
            text: "Lampen"
    
    # === HEIZUNG ===
    - id: page_heating
      bg_color: 0x000000
      pad_all: 10
      pad_top: 45
      widgets:
        - obj:
            width: 300
            height: 110
            bg_color: 0x1a1a1a
            radius: 10
            pad_all: 10
            widgets:
              - label:
                  text: "Wohnzimmer"
                  text_font: roboto_bold_18
                  align: TOP_LEFT
              - label:
                  id: wz_current_label
                  text: "-- C"
                  text_font: roboto_bold_24
                  align: CENTER
              - label:
                  id: wz_target_label
                  text: "Ziel: -- C"
                  text_font: roboto_14
                  align: BOTTOM_MID
        
        - obj:
            width: 300
            height: 110
            y: 125
            bg_color: 0x1a1a1a
            radius: 10
            pad_all: 10
            widgets:
              - label:
                  text: "Schlafzimmer"
                  text_font: roboto_bold_18
                  align: TOP_LEFT
              - label:
                  id: sz_current_label
                  text: "-- C"
                  text_font: roboto_bold_24
                  align: CENTER
              - label:
                  id: sz_target_label
                  text: "Ziel: -- C"
                  text_font: roboto_14
                  align: BOTTOM_MID
      
      on_load:
        - lvgl.label.update:
            id: page_title
            text: "Heizung"
    
    # === WETTER ===
    - id: page_weather
      bg_color: 0x000000
      pad_all: 10
      pad_top: 45
      widgets:
        - obj:
            width: 300
            height: 180
            bg_color: 0x1a1a1a
            radius: 10
            pad_all: 15
            widgets:
              - label:
                  text: "Wetter"
                  text_font: roboto_bold_24
                  align: TOP_LEFT
              - label:
                  id: weather_temp_label
                  text: "-- C"
                  text_font: roboto_bold_24
                  align: CENTER
              - label:
                  id: weather_condition_label
                  text: "--"
                  text_font: roboto_16
                  align: BOTTOM_MID
      
      on_load:
        - lvgl.label.update:
            id: page_title
            text: "Wetter"

# Header Update
interval:
  - interval: 1s
    then:
      - lvgl.label.update:
          id: time_label
          text: !lambda return id(current_time_badge).state.c_str();
      - lvgl.label.update:
          id: wifi_label
          text: !lambda |-
            int strength = (int)id(wifi_strength).state;
            if (strength > 75) return "***";
            if (strength > 50) return "** ";
            if (strength > 25) return "*  ";
            return "   ";
