# guition-display-simple.yaml
# VEREINFACHTE VERSION - Alles in einer Datei
# Teste erst diese Version, dann bauen wir aus!

esphome:
  name: guition-display
  friendly_name: Guition Display
  min_version: 2024.11.0
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: backlight
          brightness: 80%
      - delay: 1s
      - lvgl.page.show: page_lights

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

# Hardware
spi:
  - type: quad
    clk_pin: 47
    data_pins: [21, 48, 40, 39]

i2c:
  - sda: 4
    scl: 8
    scan: true

output:
  - id: gpio_backlight_pwm
    platform: ledc
    pin: 1
    frequency: 1000Hz

light:
  - id: backlight
    name: Backlight
    platform: monochromatic
    output: gpio_backlight_pwm
    restore_mode: ALWAYS_ON

display:
  - id: main_display
    platform: mipi_spi
    model: JC3248W535
    data_rate: 40MHz
    update_interval: never
    auto_clear_enabled: false

touchscreen:
  - id: main_touchscreen
    platform: axs15231

web_server:
  port: 80

time:
  - platform: homeassistant
    id: ha_time
    timezone: Europe/Berlin

# WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Guition-Display"

captive_portal:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: INFO
  logs:
    component: ERROR

# Fonts (minimal für Test)
font:
  - file: "gfonts://Roboto"
    id: roboto_16
    size: 16
    glyphs: "!\"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzäöüÄÖÜß"
  
  - file: "gfonts://Roboto@700"
    id: roboto_bold_24
    size: 24
    glyphs: "!\"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzäöüÄÖÜß"

# Sensoren
text_sensor:
  - platform: template
    id: current_time_badge
    update_interval: 1s
    lambda: |-
      auto time = id(ha_time).now();
      return str_sprintf("%02d:%02d", time.hour, time.minute);

# Minimal LVGL
lvgl:
  log_level: WARN
  displays:
    - main_display
  touchscreens:
    - touchscreen_id: main_touchscreen
  color_depth: 16
  default_font: roboto_16
  
  top_layer:
    widgets:
      - label:
          id: time_label
          x: 10
          y: 5
          text_font: roboto_bold_24
          text: "00:00"
  
  pages:
    - id: page_lights
      widgets:
        - label:
            align: CENTER
            text: "TEST✅"
            text_font: roboto_bold_24

interval:
  - interval: 1s
    then:
      - lvgl.label.update:
          id: time_label
          text: !lambda return id(current_time_badge).state.c_str();
