# guition-display.yaml
# Hauptkonfiguration für Guition ESP32-S3 3.5" Display
# Zusammengeführt aus esp_lvg_eigen und esphome-guition-display

esphome:
  name: guition-display
  friendly_name: Guition Display
  on_boot:
    priority: 600
    then:
      # Backlight einschalten
      - light.turn_on:
          id: backlight
          brightness: 80%
      # Startseite laden
      - delay: 2s
      - lvgl.page.show: ${home_page}

substitutions:
  # Startseite beim Booten (änderbar: page_lights, page_heating, page_weather)
  home_page: "page_lights"

# Gemeinsame Konfiguration einbinden
packages:
  device: !include devices/JC3248W535.yaml  # ✅ Korrekte Hardware
  common: !include common.yaml              # Standard-Sensoren & Schalter
  layout: !include layouts/480x320.yaml     # LVGL-Basis-Layout
  
  # Seiten (nach Bedarf hinzufügen/entfernen)
  lights: !include pages/lights.yaml        # Licht-Steuerung
  heating: !include pages/heating.yaml      # Heizungs-Steuerung
  weather: !include pages/weather.yaml      # Wetter-Anzeige

# WLAN-Konfiguration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Fallback Access Point bei WLAN-Problemen
  ap:
    ssid: "Guition-Display"
    password: "12345678"

# Captive Portal für WiFi-Setup
captive_portal:

# Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
  # Home Assistant IP speichern (aus common.yaml global)
  on_client_connected:
    - globals.set:
        id: homeassistant_ip
        value: !lambda return client_address;

# OTA Updates über WLAN
ota:
  - platform: esphome
    password: !secret ota_password

# Logging
logger:
  level: INFO
  logs:
    component: ERROR
    lvgl: WARN
