# guition-display.yaml
# Hauptkonfiguration für Guition ESP32-S3 3.5" Display

esphome:
  name: guition-display
  friendly_name: Guition Display
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: backlight
          brightness: 80%
      - delay: 2s
      - lvgl.page.show: page_lights

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

# === Hardware ===
spi:
  - type: quad
    clk_pin: 47
    data_pins: [21, 48, 40, 39]

i2c:
  - sda: 4
    scl: 8
    scan: true

output:
  - id: gpio_backlight_pwm
    platform: ledc
    pin: 1
    frequency: 1000Hz

light:
  - id: backlight
    name: Backlight
    platform: monochromatic
    output: gpio_backlight_pwm
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

display:
  - id: main_display
    platform: mipi_spi
    model: JC3248W535
    data_rate: 40MHz
    update_interval: never
    auto_clear_enabled: false

touchscreen:
  - id: main_touchscreen
    platform: axs15231

# === Common ===
web_server:
  port: 80

time:
  - platform: homeassistant
    id: ha_time
    timezone: Europe/Berlin

switch:
  - platform: restart
    name: "Restart"
    entity_category: config

globals:
  - id: homeassistant_ip
    type: std::string
    initial_value: '""'

# === Layouts & Pages als Includes ===
# Diese sind zu groß und werden separat geladen
font: !include layouts/fonts.yaml

# LVGL mit allen Seiten
lvgl: !include layouts/lvgl_complete.yaml

# Sensoren für Seiten
binary_sensor: !include sensors/binary.yaml
sensor: !include sensors/numeric.yaml
text_sensor: !include sensors/text.yaml

# === WLAN ===
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Guition-Display"
    password: "12345678"

captive_portal:

api:
  encryption:
    key: !secret api_encryption_key
  on_client_connected:
    - globals.set:
        id: homeassistant_ip
        value: !lambda return client_address;

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: INFO
  logs:
    component: ERROR
    lvgl: WARN
