# guition-display.yaml
# Hauptkonfiguration für Guition ESP32-S3 3.5" Display

esphome:
  name: guition-display
  friendly_name: Guition Display
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: backlight
          brightness: 80%
      - delay: 2s
      - lvgl.page.show: ${home_page}

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

substitutions:
  home_page: "page_lights"

# Single package include (Hardware + Common)
packages:
  base_config: !include all_packages.yaml

# Layout & Pages als direkte Includes (zu groß für merge)
font: !include layouts/fonts.yaml
lvgl: !include layouts/lvgl.yaml

# Seiten-spezifische Sensoren
binary_sensor: !include pages/lights_sensors.yaml
sensor: !include pages/heating_sensors.yaml
text_sensor: !include pages/weather_sensors.yaml

# WLAN
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Guition-Display"
    password: "12345678"

captive_portal:

api:
  encryption:
    key: !secret api_encryption_key
  on_client_connected:
    - globals.set:
        id: homeassistant_ip
        value: !lambda return client_address;

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: INFO
  logs:
    component: ERROR
    lvgl: WARN
