# guition-display.yaml
# Hauptkonfiguration für Guition ESP32-S3 3.5" Display
# Zusammengeführt aus esp_lvg_eigen und esphome-guition-display

esphome:
  name: guition-display
  friendly_name: Guition Display
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
  on_boot:
    priority: 600
    then:
      # Backlight einschalten
      - light.turn_on:
          id: backlight
          brightness: 80%
      # Startseite laden
      - delay: 2s
      - lvgl.page.show: ${home_page}

# ESP32 Platform - MUSS vor packages kommen!
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

substitutions:
  # Startseite beim Booten (änderbar: page_lights, page_heating, page_weather)
  home_page: "page_lights"

# Gemeinsame Konfiguration einbinden (neue List-Syntax ab ESPHome 2026.x)
packages:
  - !include devices/JC3248W535.yaml  # ✅ Korrekte Hardware
  - !include common.yaml              # Standard-Sensoren & Schalter
  - !include layouts/480x320.yaml     # LVGL-Basis-Layout
  - !include pages/lights.yaml        # Licht-Steuerung
  - !include pages/heating.yaml       # Heizungs-Steuerung
  - !include pages/weather.yaml       # Wetter-Anzeige

# WLAN-Konfiguration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Fallback Access Point bei WLAN-Problemen
  ap:
    ssid: "Guition-Display"
    password: "12345678"

# Captive Portal für WiFi-Setup
captive_portal:

# Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
  # Home Assistant IP speichern (aus common.yaml global)
  on_client_connected:
    - globals.set:
        id: homeassistant_ip
        value: !lambda return client_address;

# OTA Updates über WLAN
ota:
  - platform: esphome
    password: !secret ota_password

# Logging
logger:
  level: INFO
  logs:
    component: ERROR
    lvgl: WARN
