# guition-display.yaml
# Hauptkonfiguration für Guition ESP32-S3 3.5" Display
# Zusammengeführt aus esp_lvg_eigen und esphome-guition-display

esphome:
  name: guition-display
  friendly_name: Guition Display
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
  on_boot:
    priority: 600
    then:
      # Backlight einschalten
      - light.turn_on:
          id: backlight
          brightness: 80%
      # Startseite laden
      - delay: 2s
      - lvgl.page.show: ${home_page}

# ESP32 Platform
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

substitutions:
  home_page: "page_lights"

# Includes mit << Merge-Operator (funktioniert mit allen ESPHome-Versionen)
<<: !include devices/JC3248W535.yaml
<<: !include common.yaml
<<: !include layouts/480x320.yaml
<<: !include pages/lights.yaml
<<: !include pages/heating.yaml
<<: !include pages/weather.yaml

# WLAN-Konfiguration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Guition-Display"
    password: "12345678"

captive_portal:

api:
  encryption:
    key: !secret api_encryption_key
  on_client_connected:
    - globals.set:
        id: homeassistant_ip
        value: !lambda return client_address;

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: INFO
  logs:
    component: ERROR
    lvgl: WARN
