# guition-display-full.yaml
# VOLLSTÄNDIGE VERSION mit allen Seiten

esphome:
  name: guition-display
  friendly_name: Guition Display
  min_version: 2024.11.0
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: backlight
          brightness: 80%
      - delay: 1s
      - lvgl.page.show: page_lights

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

# === Hardware ===
spi:
  - type: quad
    clk_pin: 47
    data_pins: [21, 48, 40, 39]

i2c:
  - sda: 4
    scl: 8
    scan: true

output:
  - id: gpio_backlight_pwm
    platform: ledc
    pin: 1
    frequency: 1000Hz

light:
  - id: backlight
    name: Backlight
    platform: monochromatic
    output: gpio_backlight_pwm
    restore_mode: ALWAYS_ON

display:
  - id: main_display
    platform: mipi_spi
    model: JC3248W535
    data_rate: 40MHz
    update_interval: never
    auto_clear_enabled: false

touchscreen:
  - id: main_touchscreen
    platform: axs15231

web_server:
  port: 80

time:
  - platform: homeassistant
    id: ha_time
    timezone: Europe/Berlin

# === WiFi ===
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Guition-Display"

captive_portal:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: INFO
  logs:
    component: ERROR
    lvgl: WARN

# === FONTS (vereinfacht - keine Emojis wegen Duplikat-Problem) ===
font:
  - file: "gfonts://Roboto"
    id: roboto_16
    size: 16
    glyphs: "!\"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzäöüÄÖÜß@&/"
  
  - file: "gfonts://Roboto"
    id: roboto_20
    size: 20
    glyphs: "!\"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzäöüÄÖÜß@&/"
  
  - file: "gfonts://Roboto@700"
    id: roboto_bold_24
    size: 24
    glyphs: "!\"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzäöüÄÖÜß@&/"

# === SENSOREN ===
text_sensor:
  - platform: template
    id: current_time_badge
    update_interval: 1s
    lambda: |-
      auto time = id(ha_time).now();
      return str_sprintf("%02d:%02d", time.hour, time.minute);
  
  - platform: wifi_info
    ip_address:
      id: ip_address
      entity_category: diagnostic

sensor:
  - platform: wifi_signal
    id: wifi_signal_db
    update_interval: 60s
  
  - platform: template
    id: wifi_strength
    unit_of_measurement: "%"
    update_interval: 60s
    lambda: |-
      if (id(wifi_signal_db).state) {
        return min(max(2 * (id(wifi_signal_db).state + 100.0), 0.0), 100.0);
      } else {
        return 0.0;
      }

# Lichter-Sensoren (ANPASSEN AN DEINE ENTITÄTEN!)
binary_sensor:
  - platform: homeassistant
    entity_id: light.alle_lichter_2  # ÄNDERN!
    id: alle_lichter_state
    internal: true
    on_state:
      - lvgl.widget.update:
          id: btn_alle_lichter
          bg_color: !lambda |-
            return lv_color_hex(x ? 0xFFAA00 : 0x333333);

# === LVGL ===
lvgl:
  log_level: WARN
  displays:
    - main_display
  touchscreens:
    - touchscreen_id: main_touchscreen
  color_depth: 16
  default_font: roboto_16
  buffer_size: 25%
  
  # Header
  top_layer:
    widgets:
      - obj:
          id: header_bar
          x: 0
          y: 0
          width: 480
          height: 40
          bg_color: 0x1a1a1a
          border_width: 0
          pad_all: 5
          widgets:
            - label:
                id: time_label
                x: 10
                y: 5
                text_font: roboto_bold_24
                text: "00:00"
            - label:
                id: page_title
                align: CENTER
                text_font: roboto_20
                text: "Lampen"
            - label:
                id: wifi_label
                x: 430
                y: 5
                text_font: roboto_16
                text: "..."
  
  # Seiten
  pages:
    - id: page_lights
      bg_color: 0x000000
      pad_all: 0
      pad_top: 45
      widgets:
        - obj:
            id: btn_alle_lichter
            x: 10
            y: 50
            width: 460
            height: 80
            bg_color: 0x333333
            radius: 10
            clickable: true
            on_click:
              - homeassistant.service:
                  service: light.toggle
                  data:
                    entity_id: light.alle_lichter_2  # ÄNDERN!
            widgets:
              - label:
                  align: CENTER
                  text_font: roboto_bold_24
                  text: "Alle Lichter"
      on_load:
        - lvgl.label.update:
            id: page_title
            text: "Lampen"

# Header Update
interval:
  - interval: 1s
    then:
      - lvgl.label.update:
          id: time_label
          text: !lambda return id(current_time_badge).state.c_str();
      - lvgl.label.update:
          id: wifi_label
          text: !lambda |-
            int strength = (int)id(wifi_strength).state;
            if (strength > 75) return "***";
            if (strength > 50) return "** ";
            if (strength > 25) return "*  ";
            return "   ";
