# guition-display.yaml
# Monolithische Konfiguration (ESPHome 2026.2.0 kompatibel)
# Keine packages - alle direkt integriert

esphome:
  name: guition-display
  friendly_name: Guition Display
  min_version: 2024.11.0
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: backlight
          brightness: 80%
      - delay: 1s
      - lvgl.page.show: page_lights

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

# === Hardware ===
spi:
  - type: quad
    clk_pin: 47
    data_pins: [21, 48, 40, 39]

i2c:
  - sda: 4
    scl: 8
    scan: true

output:
  - id: gpio_backlight_pwm
    platform: ledc
    pin: 1
    frequency: 1000Hz

light:
  - id: backlight
    name: Backlight
    platform: monochromatic
    output: gpio_backlight_pwm
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

display:
  - id: main_display
    platform: mipi_spi
    model: JC3248W535
    data_rate: 40MHz
    update_interval: never
    auto_clear_enabled: false

touchscreen:
  - id: main_touchscreen
    platform: axs15231

# === Common ===
web_server:
  port: 80

time:
  - platform: homeassistant
    id: ha_time
    timezone: Europe/Berlin

switch:
  - platform: restart
    name: "Restart"
    entity_category: config

globals:
  - id: homeassistant_ip
    type: std::string
    initial_value: '""'

# === WiFi ===
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Guition-Display"
    password: "12345678"

captive_portal:

api:
  encryption:
    key: !secret api_encryption_key
  on_client_connected:
    - globals.set:
        id: homeassistant_ip
        value: !lambda return client_address;

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: INFO
  logs:
    component: ERROR
    lvgl: WARN

# === Fonts & LVGL ===
font: !include layouts/fonts.yaml
lvgl: !include layouts/lvgl_complete.yaml

# === Sensoren (ALLE in einem Block!) ===
binary_sensor:
  - platform: status
    name: "Status"
    entity_category: diagnostic
  # Seiten-Sensoren werden in pages/*.yaml eingebunden (Teil von lvgl)

sensor:
  - id: wifi_signal_db
    name: "WiFi Signal"
    platform: wifi_signal
    update_interval: 60s
    entity_category: diagnostic
  
  - platform: template
    name: "WiFi Strength"
    id: wifi_strength
    unit_of_measurement: "%"
    update_interval: 60s
    entity_category: diagnostic
    lambda: |-
      if (id(wifi_signal_db).state) {
        return min(max(2 * (id(wifi_signal_db).state + 100.0), 0.0), 100.0);
      } else {
        return 0.0;
      }

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
      id: ip_address
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
      id: connected_ssid
    mac_address:
      name: "Mac Address"
      entity_category: diagnostic
      id: mac_address
  
  - platform: template
    name: "Current Time Badge"
    id: current_time_badge
    update_interval: 1s
    lambda: |-
      auto time = id(ha_time).now();
      return str_sprintf("%02d:%02d", time.hour, time.minute);
  
  - platform: template
    name: "Current Date"
    id: current_date
    update_interval: 60s
    lambda: |-
      auto time = id(ha_time).now();
      static const char * const months[] = {"Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"};
      return str_sprintf("%02d. %s %04d", time.day_of_month, months[time.month-1], time.year);

# Header Update Timer
interval:
  - interval: 1s
    then:
      - lvgl.label.update:
          id: time_label
          text: !lambda return id(current_time_badge).state.c_str();
      - lvgl.label.update:
          id: wifi_label
          text: !lambda |-
            int strength = (int)id(wifi_strength).state;
            if (strength > 75) return "███";
            if (strength > 50) return "██░";
            if (strength > 25) return "█░░";
            return "░░░";
