# heating.yaml
# Heizungssteuerung für 3 Sonoff TRVZB Thermostate

# Home Assistant Sensoren für Heizungen
sensor:
  # Wohnzimmer
  - platform: homeassistant
    entity_id: climate.wohnzimmer_heizung
    attribute: current_temperature
    id: wohnzimmer_current_temp
    internal: true
    on_value:
      - lvgl.label.update:
          id: label_wohnzimmer_current
          text: !lambda |-
            return str_sprintf("%.1f°C", x);
  
  - platform: homeassistant
    entity_id: climate.wohnzimmer_heizung
    attribute: temperature
    id: wohnzimmer_target_temp
    internal: true
    on_value:
      - lvgl.label.update:
          id: label_wohnzimmer_target
          text: !lambda |-
            return str_sprintf("Soll: %.1f°C", x);
      - lvgl.slider.update:
          id: slider_wohnzimmer
          value: !lambda |-
            return x;
  
  - platform: homeassistant
    entity_id: sensor.wohnzimmer_heizung_battery
    id: wohnzimmer_battery
    internal: true
    on_value:
      - lvgl.label.update:
          id: label_wohnzimmer_battery
          text: !lambda |-
            return str_sprintf("🔋 %.0f%%", x);
  
  # Büro Markus
  - platform: homeassistant
    entity_id: climate.buro_markus_heizung
    attribute: current_temperature
    id: markus_current_temp
    internal: true
    on_value:
      - lvgl.label.update:
          id: label_markus_current
          text: !lambda |-
            return str_sprintf("%.1f°C", x);
  
  - platform: homeassistant
    entity_id: climate.buro_markus_heizung
    attribute: temperature
    id: markus_target_temp
    internal: true
    on_value:
      - lvgl.label.update:
          id: label_markus_target
          text: !lambda |-
            return str_sprintf("Soll: %.1f°C", x);
      - lvgl.slider.update:
          id: slider_markus
          value: !lambda |-
            return x;
  
  - platform: homeassistant
    entity_id: sensor.buro_markus_heizung_battery
    id: markus_battery
    internal: true
    on_value:
      - lvgl.label.update:
          id: label_markus_battery
          text: !lambda |-
            return str_sprintf("🔋 %.0f%%", x);
  
  # Schlafzimmer
  - platform: homeassistant
    entity_id: climate.schlafzimmer_heizung
    attribute: current_temperature
    id: schlafzimmer_current_temp
    internal: true
    on_value:
      - lvgl.label.update:
          id: label_schlafzimmer_current
          text: !lambda |-
            return str_sprintf("%.1f°C", x);
  
  - platform: homeassistant
    entity_id: climate.schlafzimmer_heizung
    attribute: temperature
    id: schlafzimmer_target_temp
    internal: true
    on_value:
      - lvgl.label.update:
          id: label_schlafzimmer_target
          text: !lambda |-
            return str_sprintf("Soll: %.1f°C", x);
      - lvgl.slider.update:
          id: slider_schlafzimmer
          value: !lambda |-
            return x;
  
  - platform: homeassistant
    entity_id: sensor.schlafzimmer_heizung_battery
    id: schlafzimmer_battery
    internal: true
    on_value:
      - lvgl.label.update:
          id: label_schlafzimmer_battery
          text: !lambda |-
            return str_sprintf("🔋 %.0f%%", x);

# Binary Sensor für Heizzustand
binary_sensor:
  - platform: homeassistant
    entity_id: climate.wohnzimmer_heizung
    attribute: hvac_action
    id: wohnzimmer_heating
    internal: true
  
  - platform: homeassistant
    entity_id: climate.buro_markus_heizung
    attribute: hvac_action
    id: markus_heating
    internal: true
  
  - platform: homeassistant
    entity_id: climate.schlafzimmer_heizung
    attribute: hvac_action
    id: schlafzimmer_heating
    internal: true

# LVGL Seite
lvgl:
  pages:
    - id: page_heating
      skip: false
      layout:
        type: flex
        flex_flow: COLUMN
      bg_color: 0x000000
      pad_all: 5
      pad_top: 50
      widgets:
        # Wohnzimmer Heizung
        - obj:
            width: 100%
            height: 85
            bg_color: 0x1a1a1a
            border_color: 0x444444
            border_width: 2
            radius: 10
            pad_all: 10
            widgets:
              - label:
                  align: TOP_LEFT
                  text_font: roboto_bold_24
                  text_color: 0xFFFFFF
                  text: "Wohnzimmer"
              
              - label:
                  id: label_wohnzimmer_current
                  align: TOP_RIGHT
                  text_font: roboto_bold_32
                  text_color: 0xFF6B00
                  text: "--.-°C"
              
              - label:
                  id: label_wohnzimmer_target
                  x: 10
                  y: 30
                  text_font: roboto_16
                  text_color: 0xAAAAAA
                  text: "Soll: --.-°C"
              
              - label:
                  id: label_wohnzimmer_battery
                  align: TOP_RIGHT
                  y: 35
                  text_font: roboto_16
                  text_color: 0xAAAAAA
                  text: "🔋 --%"
              
              - slider:
                  id: slider_wohnzimmer
                  width: 95%
                  align: BOTTOM_MID
                  y: -5
                  min_value: 5
                  max_value: 30
                  value: 20
                  on_release:
                    - homeassistant.service:
                        service: climate.set_temperature
                        data:
                          entity_id: climate.wohnzimmer_heizung
                          temperature: !lambda |-
                            return x;
        
        # Büro Markus Heizung
        - obj:
            width: 100%
            height: 85
            bg_color: 0x1a1a1a
            border_color: 0x444444
            border_width: 2
            radius: 10
            pad_all: 10
            widgets:
              - label:
                  align: TOP_LEFT
                  text_font: roboto_bold_24
                  text_color: 0xFFFFFF
                  text: "Büro Markus"
              
              - label:
                  id: label_markus_current
                  align: TOP_RIGHT
                  text_font: roboto_bold_32
                  text_color: 0xFF6B00
                  text: "--.-°C"
              
              - label:
                  id: label_markus_target
                  x: 10
                  y: 30
                  text_font: roboto_16
                  text_color: 0xAAAAAA
                  text: "Soll: --.-°C"
              
              - label:
                  id: label_markus_battery
                  align: TOP_RIGHT
                  y: 35
                  text_font: roboto_16
                  text_color: 0xAAAAAA
                  text: "🔋 --%"
              
              - slider:
                  id: slider_markus
                  width: 95%
                  align: BOTTOM_MID
                  y: -5
                  min_value: 5
                  max_value: 30
                  value: 20
                  on_release:
                    - homeassistant.service:
                        service: climate.set_temperature
                        data:
                          entity_id: climate.buro_markus_heizung
                          temperature: !lambda |-
                            return x;
        
        # Schlafzimmer Heizung
        - obj:
            width: 100%
            height: 85
            bg_color: 0x1a1a1a
            border_color: 0x444444
            border_width: 2
            radius: 10
            pad_all: 10
            widgets:
              - label:
                  align: TOP_LEFT
                  text_font: roboto_bold_24
                  text_color: 0xFFFFFF
                  text: "Schlafzimmer"
              
              - label:
                  id: label_schlafzimmer_current
                  align: TOP_RIGHT
                  text_font: roboto_bold_32
                  text_color: 0xFF6B00
                  text: "--.-°C"
              
              - label:
                  id: label_schlafzimmer_target
                  x: 10
                  y: 30
                  text_font: roboto_16
                  text_color: 0xAAAAAA
                  text: "Soll: --.-°C"
              
              - label:
                  id: label_schlafzimmer_battery
                  align: TOP_RIGHT
                  y: 35
                  text_font: roboto_16
                  text_color: 0xAAAAAA
                  text: "🔋 --%"
              
              - slider:
                  id: slider_schlafzimmer
                  width: 95%
                  align: BOTTOM_MID
                  y: -5
                  min_value: 5
                  max_value: 30
                  value: 20
                  on_release:
                    - homeassistant.service:
                        service: climate.set_temperature
                        data:
                          entity_id: climate.schlafzimmer_heizung
                          temperature: !lambda |-
                            return x;
      
      on_load:
        - lvgl.label.update:
            id: page_title
            text: "🌡️ Heizung"