# pages/weather.yaml
# Beispiel-Seite f체r Wetter-Anzeige
# TODO: Passe die entity_id an deine Wetter-Integration an!

sensor:
  - platform: homeassistant
    id: weather_temperature
    entity_id: weather.home
    attribute: temperature
    on_value:
      - lvgl.label.update:
          id: label_weather_temp
          text: !lambda |-
            return str_sprintf("%.1f째C", x);

text_sensor:
  - platform: homeassistant
    id: weather_condition
    entity_id: weather.home
    attribute: condition
    on_value:
      - lvgl.label.update:
          id: label_weather_condition
          text: !lambda |-
            return x.c_str();

lvgl:
  pages:
    - id: page_weather
      widgets:
        - label:
            id: label_weather_title
            x: 10
            y: 10
            text: "Wetter"
            text_font: roboto_16
        
        # Temperatur
        - label:
            id: label_weather_temp
            x: 10
            y: 50
            text: "--.-째C"
            text_font: roboto_32
        
        # Wetter-Zustand
        - label:
            id: label_weather_condition
            x: 10
            y: 100
            text: "Lade..."
            text_font: roboto_16
        
        # TODO: F체ge weitere Wetter-Daten hinzu (Wind, Luftfeuchtigkeit, etc.)
